# generated by datamodel-codegen:
#   filename:  userProfile.schema.json
#   timestamp: 2025-06-30T02:11:31+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class UserProfile(BaseModel):
    userId: str = Field(..., description='The unique ID of the user (from Discord).')
    displayName: str = Field(..., description="The user's display name.")
    createdAt: float = Field(
        ..., description='The timestamp when the profile was created.'
    )
    favoriteThings: Optional[List[str]] = Field(
        None, description="A list of the user's favorite things."
    )
