/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A history record of attack data.
 */
export interface AttackHistory {
  /**
   * The member ID who performed the attack.
   */
  member: number;
  /**
   * The day of the attack.
   */
  day: number;
  /**
   * The sortie information.
   */
  sortie: number;
  /**
   * The message ID related to the attack.
   */
  messageid: string;
  /**
   * The boss that was attacked.
   */
  boss: number;
  /**
   * Whether the attack was during overtime.
   */
  overtime: boolean;
  /**
   * Whether the boss was defeated.
   */
  defeat: boolean;
  /**
   * The number of sorties.
   */
  sortiecount: number;
  /**
   * The timestamp when the record was updated.
   */
  updatetime: string;
  [k: string]: unknown;
}
