/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A user profile stored in Firebase.
 */
export interface UserProfile {
  /**
   * The unique ID of the user (from Google).
   */
  googleUserId: string;
  /**
   * The unique ID of the user (from Discord).
   */
  discordId?: string | null;
  /**
   * The unique ID of the Discord server the user belongs to.
   */
  discordServer?: string | null;
  /**
   * The user's display name.
   */
  displayName: string;
  /**
   * The timestamp when the profile was created.
   */
  createdAt: number;
  /**
   * The user's role (managed by server only). Set by Admin SDK only, not directly editable by users.
   */
  role?: "user" | "admin";
  [k: string]: unknown;
}
