/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A user profile stored in Firebase.
 */
export interface UserProfile {
  /**
   * The unique ID of the user (from Discord).
   */
  userId: string;
  /**
   * The user's display name.
   */
  displayName: string;
  /**
   * The timestamp when the profile was created.
   */
  createdAt: number;
  /**
   * A list of the user's favorite things.
   */
  favoriteThings?: string[];
  [k: string]: unknown;
}
